# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('first_name', models.CharField(max_length=64, verbose_name='first name')),
                ('last_name', models.CharField(max_length=64, verbose_name='last name')),
                ('season', models.CharField(max_length=16, verbose_name='season')),
                ('ranking_mu', models.FloatField(default=None, null=True, verbose_name='Ranking MU')),
                ('ranking_sigma', models.FloatField(default=None, null=True, verbose_name='Ranking SIGMA')),
                ('PERSON_ID', models.PositiveIntegerField(unique=True, verbose_name='PERSON_ID')),
                ('PLAYERCODE', models.CharField(max_length=128, unique=True, verbose_name='PLAYERCODE')),
                ('ROSTERSTATUS', models.PositiveSmallIntegerField(verbose_name='ROSTERSTATUS')),
                ('GAMES_PLAYED_FLAG', models.CharField(max_length=8, verbose_name='GAMES_PLAYED_FLAG')),
            ],
            options={
                'verbose_name': 'player',
                'verbose_name_plural': 'players',
                'ordering': ['-ranking_mu', 'ranking_sigma'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('city', models.CharField(max_length=128, verbose_name='city')),
                ('abbr', models.CharField(max_length=8, verbose_name='abbreviation')),
                ('TEAM_ID', models.PositiveIntegerField(unique=True, verbose_name='TEAM_ID')),
                ('TEAM_CODE', models.CharField(max_length=128, unique=True, verbose_name='TEAM_CODE')),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='players.Team', verbose_name='team'),
        ),
    ]
