# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('first_name', models.CharField(max_length=64, verbose_name='first name')),
                ('last_name', models.CharField(max_length=64, verbose_name='last name')),
                ('photo', models.ImageField(null=True, upload_to='players_photos', verbose_name='photo')),
                ('PERSON_ID', models.PositiveIntegerField(unique=True, verbose_name='PERSON_ID')),
                ('PLAYERCODE', models.CharField(max_length=128, unique=True, verbose_name='PLAYERCODE')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'verbose_name': 'player',
                'verbose_name_plural': 'players',
            },
        ),
        migrations.CreateModel(
            name='PlayerSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('season', models.CharField(max_length=16, verbose_name='season')),
                ('rating_mu', models.FloatField(default=None, null=True, verbose_name='Rating MU')),
                ('rating_sigma', models.FloatField(default=None, null=True, verbose_name='Rating SIGMA')),
                ('pts', models.FloatField(verbose_name='PTS')),
                ('reb', models.FloatField(verbose_name='REB')),
                ('ast', models.FloatField(verbose_name='AST')),
                ('stl', models.FloatField(verbose_name='STL')),
                ('blk', models.FloatField(verbose_name='BLK')),
                ('fg_pct', models.FloatField(verbose_name='FG%')),
                ('fg3_pct', models.FloatField(verbose_name='3P%')),
                ('ft_pct', models.FloatField(verbose_name='FT%')),
                ('ROSTERSTATUS', models.PositiveSmallIntegerField(verbose_name='ROSTERSTATUS')),
                ('GAMES_PLAYED_FLAG', models.CharField(max_length=8, verbose_name='GAMES_PLAYED_FLAG')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='players.Player', verbose_name='player')),
            ],
            options={
                'verbose_name': 'player season',
                'ordering': ['-season', '-rating_mu', 'rating_sigma'],
                'verbose_name_plural': 'player seasons',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('city', models.CharField(max_length=128, verbose_name='city')),
                ('abbr', models.CharField(max_length=8, verbose_name='abbreviation')),
                ('TEAM_ID', models.PositiveIntegerField(unique=True, verbose_name='TEAM_ID')),
                ('TEAM_CODE', models.CharField(max_length=128, unique=True, verbose_name='TEAM_CODE')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
            },
        ),
        migrations.AddField(
            model_name='playerseason',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players_seasons', to='players.Team', verbose_name='team'),
        ),
        migrations.AlterUniqueTogether(
            name='playerseason',
            unique_together=set([('player', 'season')]),
        ),
    ]
