# Generated by Django 2.1.2 on 2018-10-15 22:00

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('first_name', models.CharField(max_length=64, verbose_name='first name')),
                ('last_name', models.CharField(max_length=64, verbose_name='last name')),
                ('photo', models.ImageField(null=True, upload_to='players_photos', verbose_name='photo')),
                ('PERSON_ID', models.PositiveIntegerField(unique=True, verbose_name='PERSON_ID')),
                ('PLAYERCODE', models.CharField(max_length=128, unique=True, verbose_name='PLAYERCODE')),
            ],
            options={
                'verbose_name': 'player',
                'verbose_name_plural': 'players',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
