# Generated by Django 2.1.2 on 2018-10-15 22:00

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('city', models.CharField(max_length=128, verbose_name='city')),
                ('abbr', models.CharField(max_length=8, verbose_name='abbreviation')),
                ('TEAM_ID', models.PositiveIntegerField(unique=True, verbose_name='TEAM_ID')),
                ('TEAM_CODE', models.CharField(max_length=128, unique=True, verbose_name='TEAM_CODE')),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
                'ordering': ['name'],
            },
        ),
    ]
